clc;
clear all;
close all;

headers = {'Outlook', 'Temperature', 'Humidity', 'Wind'}';
options{1} = {'Sunny', 'Overcast', 'Rain'};
options{2} = {'Hot', 'Mild', 'Cool'};
options{3} = {'High', 'Normal'};
options{4} = {'Weak', 'Strong'};
options = options';
k = 1;
all_data{k} = {'Sunny', 'Hot', 'High', 'Weak'};
all_results{k} = 'No'; k = k + 1;
all_data{k} = {'Sunny', 'Hot', 'High', 'Strong'};
all_results{k} = 'No'; k = k + 1;
all_data{k} = {'Overcast', 'Hot', 'High', 'Weak'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Rain', 'Mild', 'High', 'Weak'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Rain', 'Cool', 'Normal', 'Weak'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Rain', 'Cool', 'Normal', 'Strong'};
all_results{k} = 'No'; k = k + 1;
all_data{k} = {'Overcast', 'Cool', 'Normal', 'Strong'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Sunny', 'Mild', 'High', 'Weak'};
all_results{k} = 'No'; k = k + 1;
all_data{k} = {'Sunny', 'Cool', 'Normal', 'Weak'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Rain', 'Mild', 'Normal', 'Weak'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Sunny', 'Mild', 'Normal', 'Strong'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Overcast', 'Mild', 'High', 'Strong'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Overcast', 'Hot', 'Normal', 'Weak'};
all_results{k} = 'Yes'; k = k + 1;
all_data{k} = {'Rain', 'Mild', 'High', 'Strong'};
all_results{k} = 'No'; k = k + 1;
all_data = all_data';
all_results = all_results';

disp('Done loading data');
disp('=====================================');