clc;
clear all;
close all;

% Example from class
% headers = {'Outlook', 'Temperature', 'Humidity', 'Wind'}';
% options{1} = {'Sunny', 'Overcast', 'Rain'};
% options{2} = {'Hot', 'Mild', 'Cool'};
% options{3} = {'High', 'Normal'};
% options{4} = {'Weak', 'Strong'};
% options = options';
% k = 1;
% all_data{k} = {'Sunny', 'Hot', 'High', 'Weak'};
% all_results{k} = 'No'; k = k + 1;
% all_data{k} = {'Sunny', 'Hot', 'High', 'Strong'};
% all_results{k} = 'No'; k = k + 1;
% all_data{k} = {'Overcast', 'Hot', 'High', 'Weak'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rain', 'Mild', 'High', 'Weak'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rain', 'Cool', 'Normal', 'Weak'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rain', 'Cool', 'Normal', 'Strong'};
% all_results{k} = 'No'; k = k + 1;
% all_data{k} = {'Overcast', 'Cool', 'Normal', 'Strong'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Sunny', 'Mild', 'High', 'Weak'};
% all_results{k} = 'No'; k = k + 1;
% all_data{k} = {'Sunny', 'Cool', 'Normal', 'Weak'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rain', 'Mild', 'Normal', 'Weak'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Sunny', 'Mild', 'Normal', 'Strong'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Overcast', 'Mild', 'High', 'Strong'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Overcast', 'Hot', 'Normal', 'Weak'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rain', 'Mild', 'High', 'Strong'};
% all_results{k} = 'No'; k = k + 1;
% all_data = all_data';
% all_results = all_results';

% 2014 exam
% headers = {'Outlook', 'CompanySize', 'ShipSize'}';
% options{1} = {'Sunny', 'Rainy'};
% options{2} = {'Large', 'Medium', 'Small'};
% options{3} = {'Normal', 'Big'};
% options = options';
% k = 1;
% all_data{k} = {'Sunny', 'Large', 'Normal'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Sunny', 'Medium', 'Normal'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Sunny', 'Medium', 'Big'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Sunny', 'Small', 'Normal'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Sunny', 'Large', 'Big'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rainy', 'Small', 'Normal'};
% all_results{k} = 'No'; k = k + 1;
% all_data{k} = {'Rainy', 'Medium', 'Normal'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rainy', 'Large', 'Big'};
% all_results{k} = 'Yes'; k = k + 1;
% all_data{k} = {'Rainy', 'Small', 'Big'};
% all_results{k} = 'No'; k = k + 1;
% all_data{k} = {'Rainy', 'Medium', 'Big'};
% all_results{k} = 'No'; k = k + 1;
% all_data = all_data';
% all_results = all_results';

% 2013 exam
headers = {'Age', 'Income', 'IsStudent', 'CreditRating'}';
options{1} = {'<30', '31...40', '>40'};
options{2} = {'High', 'Medium', 'Low'};
options{3} = {'No', 'Yes'};
options{4} = {'Fair', 'Excellent'};
outcomes = {'No', 'Yes'};
options = options';
k = 1;
all_data{k} = {options{1}{1}, options{2}{1}, options{3}{1}, options{4}{1}};
all_results{k} = outcomes{1}; k = k + 1;
all_data{k} = {options{1}{1}, options{2}{1}, options{3}{1}, options{4}{2}};
all_results{k} = outcomes{1}; k = k + 1;
all_data{k} = {options{1}{2}, options{2}{1}, options{3}{1}, options{4}{1}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{3}, options{2}{2}, options{3}{1}, options{4}{1}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{3}, options{2}{3}, options{3}{2}, options{4}{1}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{3}, options{2}{3}, options{3}{2}, options{4}{2}};
all_results{k} = outcomes{1}; k = k + 1;
all_data{k} = {options{1}{2}, options{2}{3}, options{3}{2}, options{4}{2}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{1}, options{2}{2}, options{3}{1}, options{4}{1}};
all_results{k} = outcomes{1}; k = k + 1;
all_data{k} = {options{1}{1}, options{2}{3}, options{3}{2}, options{4}{1}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{3}, options{2}{2}, options{3}{2}, options{4}{1}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{1}, options{2}{2}, options{3}{2}, options{4}{2}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{2}, options{2}{2}, options{3}{1}, options{4}{2}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{2}, options{2}{1}, options{3}{2}, options{4}{1}};
all_results{k} = outcomes{2}; k = k + 1;
all_data{k} = {options{1}{3}, options{2}{2}, options{3}{1}, options{4}{2}};
all_results{k} = outcomes{1}; k = k + 1;
all_data = all_data';
all_results = all_results';

disp('Done loading data');
disp('=====================================');